-- Seed Orders
-- Creates ~200 realistic orders over 90 days
-- Distribution: 10 open, 180 closed, 10 cancelled
-- Realistic date/time distribution with peak hours

DO $$
DECLARE
  v_user_id UUID;
  v_order_id UUID;
  v_days_ago INTEGER;
  v_hour INTEGER;
  v_created_at TIMESTAMPTZ;
  v_customer_names TEXT[] := ARRAY[
    'Ana Silva', 'Bruno Costa', 'Carla Souza', 'Daniel Lima', 'Elena Martins',
    'Fernando Santos', 'Gabriela Oliveira', 'Henrique Alves', 'Isabela Rocha', 'João Pereira',
    'Karina Dias', 'Lucas Fernandes', 'Mariana Castro', 'Nicolas Barbosa', 'Olivia Cardoso',
    'Paulo Ribeiro', 'Rafaela Gomes', 'Rodrigo Monteiro', 'Sofia Araújo', 'Thiago Carvalho',
    'Vanessa Teixeira', 'Wellington Freitas', 'Yasmin Nascimento', 'Zeca Barros', 'Adriana Pinto',
    'Bernardo Melo', 'Camila Cunha', 'Diego Azevedo', 'Elaine Moreira', 'Fabio Correia',
    'Giovana Ramos', 'Heitor Nogueira', 'Iris Rodrigues', 'Julio Batista', 'Larissa Campos',
    'Marcos Vieira', 'Natalia Duarte', 'Otavio Pacheco', 'Priscila Xavier', 'Renato Farias'
  ];
  v_customer_name TEXT;
  v_display_id TEXT;
  v_status TEXT;
  v_closed_at TIMESTAMPTZ;
  v_cancelled_at TIMESTAMPTZ;
  v_cancellation_reason TEXT;
  v_stock_returned BOOLEAN;
  v_open_count INTEGER := 0;
  v_closed_count INTEGER := 0;
  v_cancelled_count INTEGER := 0;
  v_total_count INTEGER := 200;
  v_order_ids UUID[];
  v_weight NUMERIC;
BEGIN
  -- Get test user ID
  SELECT id INTO v_user_id
  FROM auth.users
  WHERE email = 'test@example.com';

  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Test user not found. Run 01_test_user.sql first.';
  END IF;

  -- Delete existing orders for idempotency
  DELETE FROM api.orders WHERE user_id = v_user_id;

  -- Generate orders with realistic distribution
  FOR i IN 1..v_total_count LOOP
    -- Determine order status (10 open, 10 cancelled, rest closed)
    IF i <= 10 THEN
      v_status := 'open';
      v_open_count := v_open_count + 1;
    ELSIF i <= 20 THEN
      v_status := 'cancelled';
      v_cancelled_count := v_cancelled_count + 1;
    ELSE
      v_status := 'closed';
      v_closed_count := v_closed_count + 1;
    END IF;

    -- Realistic date distribution (weighted toward recent)
    -- Use exponential distribution: more recent = more orders
    v_weight := random();
    v_days_ago := CASE
      WHEN v_status = 'open' THEN floor(random() * 2)::int  -- Open orders: last 2 days
      WHEN v_weight < 0.4 THEN floor(random() * 7)::int      -- 40% in last week
      WHEN v_weight < 0.7 THEN 7 + floor(random() * 23)::int -- 30% in weeks 2-4
      ELSE 30 + floor(random() * 60)::int                     -- 30% in days 31-90
    END;

    -- Realistic time distribution (peak hours: 11am-2pm, 6pm-9pm)
    v_weight := random();
    v_hour := CASE
      WHEN v_weight < 0.3 THEN 11 + floor(random() * 4)::int  -- 30% lunch (11am-2pm)
      WHEN v_weight < 0.6 THEN 18 + floor(random() * 4)::int  -- 30% dinner (6pm-9pm)
      WHEN v_weight < 0.8 THEN 8 + floor(random() * 3)::int   -- 20% breakfast (8am-10am)
      ELSE 15 + floor(random() * 3)::int                       -- 20% afternoon (3pm-5pm)
    END;

    v_created_at := now()
      - (v_days_ago || ' days')::interval
      - ((v_hour || ' hours')::interval)
      - (floor(random() * 60)::int || ' minutes')::interval;

    -- Random customer name
    v_customer_name := v_customer_names[1 + floor(random() * array_length(v_customer_names, 1))::int];

    -- Generate unique display ID
    v_display_id := NULL; -- Will be auto-generated by function

    -- Set closed/cancelled timestamps
    v_closed_at := NULL;
    v_cancelled_at := NULL;
    v_cancellation_reason := NULL;
    v_stock_returned := NULL;

    IF v_status = 'closed' THEN
      -- Closed 30min to 3 hours after creation
      v_closed_at := v_created_at + (30 + floor(random() * 150)::int || ' minutes')::interval;
    ELSIF v_status = 'cancelled' THEN
      -- Cancelled 10min to 2 hours after creation
      v_cancelled_at := v_created_at + (10 + floor(random() * 110)::int || ' minutes')::interval;
      v_stock_returned := random() < 0.6; -- 60% return stock
      v_cancellation_reason := CASE floor(random() * 4)::int
        WHEN 0 THEN 'Customer request'
        WHEN 1 THEN 'Wrong order'
        WHEN 2 THEN 'Out of stock'
        ELSE 'Payment issue'
      END;
    END IF;

    -- Insert order (total_amount will be calculated later from order_items)
    INSERT INTO api.orders (
      id, user_id, customer_name, status,
      created_at, closed_at, cancelled_at,
      cancellation_reason, stock_returned, updated_at
    )
    VALUES (
      gen_random_uuid(), v_user_id, v_customer_name, v_status,
      v_created_at, v_closed_at, v_cancelled_at,
      v_cancellation_reason, v_stock_returned, v_created_at
    )
    RETURNING id INTO v_order_id;

    -- Store order ID for next seed file
    v_order_ids := array_append(v_order_ids, v_order_id);
  END LOOP;

  RAISE NOTICE 'Created % orders: % open, % closed, % cancelled',
    v_total_count, v_open_count, v_closed_count, v_cancelled_count;
END $$;
